Capture ipmitool errors and make syslog plus mail to root

diff --git a/power_save/power_ipmi b/power_save/power_ipmi
--- a/power_save/power_ipmi
+++ b/power_save/power_ipmi
@@ -18,6 +18,8 @@ BMC_SUFFIX="b"
 # Logfile for IPMI suspend/resume actions
 # N.B.: Make sure this file is writable by SlurmUser
 export LOGFILE=/var/log/slurm/power_ipmi.log
+# The slurm user
+slurmuser="slurm"
 
 # We require the "nodeset" command from the ClusterShell package.  Install it by:
 # yum install epel-release
@@ -85,16 +87,23 @@ fi
 # Loop over nodelist that performs ipmitool actions
 function nodeloop () {
 	# Usage: nodeloop cmd nodelist
-	cmd=$1	# The ipmitool chassis power cmd
-	# Expand the nodelist $2 as individual node names 
+	cmd=$1	# The action command (arg 1)
+	# Expand the nodelist (arg 2) as individual node names 
 	for node in `nodeset --expand $2`
 	do
 		# BMC DNS-name is the node name plus the string $BMC_SUFFIX
 		nodebmc=${node}${BMC_SUFFIX}
 		if $PING ${nodebmc} >/dev/null 2>&1 
 		then
-			# Make sure to get output as a single command:
-			echo "`date +'%b %d %T'` node $node ipmitool `ipmitool -I lanplus -U $IPMI_USER -P $IPMI_PASSWORD -H ${nodebmc} chassis power $cmd 2>&1`"
+			response="`ipmitool -I lanplus -U $IPMI_USER -P $IPMI_PASSWORD -H ${nodebmc} chassis power $cmd 2>&1`"
+			# Check for errors and send to syslog and mail to root
+			if test $? -ne 0
+			then
+				message="slurmctld command $0 for node $node gave response: $response"
+				logger -p user.err "$message"
+				echo "$message" | /usr/bin/mailx -s "Slurm IPMI error for node $node" root
+			fi
+			echo "`date +'%b %d %T'` node $node ipmitool $response"
 		else
 			echo "`date +'%b %d %T'` Cannot ping node ${node} BMC hostname ${nodebmc} !"
 		fi
@@ -118,7 +127,7 @@ fi
 
 # Make sure the LOGFILE is owned by SlurmUser and has correct permissions
 touch $LOGFILE
-chown slurm: $LOGFILE
+chown $slurmuser: $LOGFILE
 chmod 644 $LOGFILE
 
 # Do the resume or suspend action:
@@ -135,12 +144,14 @@ fi
 # Display $action in UPPER case (see the bash man-page under Case modification)
 echo "$DATE POWER ${action^^} the IPMI based nodelist $nodelist ($nodecount nodes)" 
 
-if [[ "$action" = "off" ]]
-then
-	# First make a soft OS shutdown and wait some seconds for completion
-	nodeloop "soft" $nodelist
-	sleep 60
-fi
+# This may not be reliable for OS shutdown:
+# Error: ipmitool Set Chassis Power Control to Down/Off failed: Command not supported in present state
+#if [[ "$action" = "off" ]]
+#then
+#	# First make a soft OS shutdown and wait some seconds for completion
+#	nodeloop "soft" $nodelist
+#	sleep 60
+#fi
 
 # Power nodes on or off
 nodeloop $action $nodelist
